# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.7
    container_name: news_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypasswd
    ports:
      - 3306:3306
